openapi: 3.0.0
info:
  title: Trail Service API
  description: API for COMP2001 CW2
  version: 1.0.0

paths:
  /health:
    get:
      operationId: "app.home"
      summary: "Check API health"
      responses:
        "200":
          description: "API is running"

  /trails:
    # 1. GET Operation (Read All)
    get:
      operationId: "trails.read_all"
      tags:
        - "Trails"
      summary: "Read the list of all trails"
      responses:
        "200":
          description: "Successfully read trail list"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Trail"

    # 2. POST Operation (Create) 
    post:
      operationId: "trails.create"
      tags:
        - "Trails"
      summary: "Create a new trail"
      parameters:
        - in: header
          name: X-Email
          schema:
            type: string
          required: true
        - in: header
          name: X-Password
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail created successfully"
        "401":
          description: "Authentication failed"

components:
  schemas:
    Trail:
      type: "object"
      properties:
        TrailId:
          type: "integer"
        TrailName:
          type: "string"
        Length:
          type: "number"
          format: "float"
        ElevationGain:
          type: "number"
          format: "float"
        EstimatedTime:
          type: "number"
          format: "float"
        RouteType:
          type: "string"
        Difficulty:
          type: "string"
        trailDescription:
          type: "string"
        OwnerId:
          type: "integer"